### ISSUE TITLE
Showing battery percentage in taskbar icon

### ISSUE THREAD

**Issue by Legnatbird** [Sandip124/BatteryNotifier#35]
It's possible make the icon in the taskbar show the actual battery percentage, and makes this icon bigger that i want?

**Comment by Sandip124** [comment]
Thanks for the suggestion @Legnatbird . i was recently realizing this.   i will put this in another version and also there are a lot of feature coming soon 😊

**Comment by Sandip124** [comment]
@Legnatbird  added setting for showing battery percentage on icon . it will be available in v 2.2.0. Enjoy ✌
