### ISSUE TITLE
Battery Notify Error

### ISSUE THREAD

**Issue by Legnatbird** [Sandip124/BatteryNotifier#45]
**Is the first time i get this error so idk if is the new version of the program**

When i restart my pc and the program execute automatically i get this error and his closes
![image](https://user-images.githubusercontent.com/50637445/177045019-45dc6ff0-2f69-4364-8a0c-5d44772be5fb.png)

But if i try to run the program normal his open normal and not get errors

**Comment by Sandip124** [comment]
this error is  due to missing fonts and  i have recently fixed in v2.0.2. is your version latest?   it is fixed now in my machine  also in startup senario

**Comment by Legnatbird** [comment]
Oh my bad, the program says restart to updated.
Now i close this issue it's useless ahaha 😥

**Comment by Legnatbird** [comment]
Hmmm, when i do right click that open the program and not is possible see the menu for close the application, its a bug or a feature 🤣?

**Comment by Sandip124** [comment]
Yeah that was bug and now fixed in v 2.0.3.
