### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Alfredoxrock** [Sandip124/BatteryNotifier#48]
Do you think you can add a saver mode?
Where the computer will low the brightness,
Slow down the processor peek usage, 
or some other ways to save energy by just clicking the saver mode button.

**Comment by Sandip124** [comment]
Thanks for suggestion @Alfredoxrock  but  may be it's not good idea to put this in this app. as it is just for notifiation  for over and under charging. 
and also the batter saver configured in  window machine easily. so why reinvent wheel?
