### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by jeanhemarre** [Sandip124/BatteryNotifier#58]
Hello,

Randomly I get this error now, and sometimes it closes the batterynotifier app, sometimes no.
I've try reinstalling some of microsoft NET things but doesn't seem to work, any ideas?
Thanks :

************** Texte de l'exception **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (8): Les ressources mémoire disponibles sont insuffisantes pour traiter cette commande.
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at BatteryNotifier.Properties.Resources.get_batteryNotifierIcon() in I:\MyProjects\BatteryNotifier\Properties\Resources.Designer.cs:line 77
   at BatteryNotifier.Forms.Dashboard.RenderIcon(Boolean isCharging) in I:\MyProjects\BatteryNotifier\Forms\Dashboard.cs:line 961
   at BatteryNotifier.Forms.Dashboard.RefreshBatteryStatus() in I:\MyProjects\BatteryNotifier\Forms\Dashboard.cs:line 532
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
System.Private.CoreLib
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Private.CoreLib.dll
----------------------------------------
BatteryNotifier
    Version de l'assembly : 2.2.1.0
    Version Win32 : 2.2.1.0
    CodeBase : file:///C:/Users/ultra/AppData/Local/BatteryNotifier/app-2.2.1/BatteryNotifier.dll
----------------------------------------
System.Runtime
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.dll
----------------------------------------
System.Threading
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Threading.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.922.41910
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.922.41910
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Collections.Specialized.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.ObjectModel.dll
----------------------------------------
Squirrel
    Version de l'assembly : 1.9.0.0
    Version Win32 : 1.9.0.0
    CodeBase : file:///C:/Users/ultra/AppData/Local/BatteryNotifier/app-2.2.1/Squirrel.dll
----------------------------------------
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/mscorlib.dll
----------------------------------------
Splat
    Version de l'assembly : 1.6.2.0
    Version Win32 : 1.6.2
    CodeBase : file:///C:/Users/ultra/AppData/Local/BatteryNotifier/app-2.2.1/Splat.dll
----------------------------------------
NuGet.Squirrel
    Version de l'assembly : 3.0.0.0
    Version Win32 : 3.0.0.0
    CodeBase : file:///C:/Users/ultra/AppData/Local/BatteryNotifier/app-2.2.1/NuGet.Squirrel.dll
----------------------------------------
System.Collections
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Collections.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Private.Uri
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Memory
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Memory.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Linq
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Linq.dll
----------------------------------------
System.Xml.ReaderWriter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Threading.Thread
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Threading.Thread.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Xml.XmlSerializer.dll
----------------------------------------
System.Diagnostics.TraceSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Windows.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Windows.Extensions.dll
----------------------------------------
System.Resources.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Resources.Extensions.dll
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/Microsoft.Win32.Primitives.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41910
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/Accessibility.dll
----------------------------------------
System.ComponentModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.ComponentModel.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.922.41910
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/System.Drawing.dll
----------------------------------------
System.Numerics.Vectors
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Net.Requests
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.Http
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.Http.dll
----------------------------------------
System.Diagnostics.Tracing
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Diagnostics.Tracing.dll
----------------------------------------
System.Collections.Concurrent
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Collections.Concurrent.dll
----------------------------------------
System.Net.ServicePoint
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Collections.NonGeneric
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Collections.NonGeneric.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Sockets
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Net.NameResolution.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Core.dll
----------------------------------------
System.Threading.Overlapped
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Threading.Overlapped.dll
----------------------------------------
System.Threading.ThreadPool
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Principal.Windows
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Linq.Expressions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Linq.Expressions.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Private.CoreLib.dll
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.Serialization.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Web
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Web.dll
----------------------------------------
System.Web.HttpUtility
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Web.HttpUtility.dll
----------------------------------------
Microsoft.Win32.Registry
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/Microsoft.Win32.Registry.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Diagnostics.Process
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.Loader
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.922.41910
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.9/fr/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.922.41905
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.9/System.Collections.Immutable.dll
----------------------------------------

************** Débogage JIT **************

**Comment by Sandip124** [comment]
This issue is from the rendering icon,  for this you can disable 'show percentage in icon ' options
which can be accessed  on context menu on notification bar.
![image](https://user-images.githubusercontent.com/37034590/193556483-d863e400-3305-4cf5-bebe-3498ba2741fa.png)
 for now you can set it off , just by clicking

**Comment by Sandip124** [comment]
Also the issue was due to insufficient memory ,  and also i found that there was memory leak when rendering icon , i have fixed this in the release  [v2.2.2](https://github.com/Sandip124/BatteryNotifier/releases/tag/v2.2.2) you restart you app to automatically update to v2.2.2.
Lastly thanks for Issue 🤟
