### ISSUE TITLE
Not working on Windows 11 21H2

### ISSUE THREAD

**Issue by psbhullar** [Sandip124/BatteryNotifier#66]
The tray icon for this app after some time vanishes, for it to work again, have to re-run the setup. Tried versions 2.2.4 and 2.2.3, app behavior remains the same. Is this just with me or others too are facing this issue?

**Comment by Sandip124** [comment]
@psbhullar  please refer https://github.com/Sandip124/BatteryNotifier/releases/tag/v3.0.0 this for latest bug fixes.
