### ISSUE TITLE
Issue with battery notifier 2020

### ISSUE THREAD

**Issue by clickey** [Sandip124/BatteryNotifier#69]
Used a Zedge low battery notification Fem 30, but it kept repeating the sound. Removed the file in the notifier app, uninstalled all sounds from every location possible, keeping the ones I know are ok. Uninstalled battery notifier, still repeats, and it's never accurate either. Pixel 4a, Android 13. Norton's security via BT virus protect. Caches all cleared. No SD card. 
No idea what to do except a reluctant reset of device.

**Comment by Sandip124** [comment]
@clickey i have addressed this in the latest release https://github.com/Sandip124/BatteryNotifier/releases/tag/v3.0.0 please download and give it a try. hope it fixes your issue
