### ISSUE TITLE
Percentage icon in tray not works

### ISSUE THREAD

**Issue by matedon** [Sandip124/BatteryNotifier#71]
I am started to use this app now. Version 2.2.4.
Thicked "Show percentage in tray icon"
Doesn't do anythng. The icon is just green with a lightning sign.
Windows 10.

**Comment by Sandip124** [comment]
@matedon  i have realized that this Feature (Show Percentage in tray icon) has caused a lot of trouble on too much RAM consumption so it is removed on the https://github.com/Sandip124/BatteryNotifier/releases/tag/v3.0.0 for the sake of performance, i am sorry to announce this feature is not anymore, as we know that the percentage in icon is redundant and is not required on the tray icon itself. and also this app aims to be simple and beautiful so, just cleaning up the mesh. thanks for opensource.
