### ISSUE TITLE
How to start..

### ISSUE THREAD

**Issue by Gevaarlijk** [Sandip124/BatteryNotifier#77]
Downloaded this software, there is no executable and the readme doesn't provide information. So how do I launch this software?

**Comment by Sandip124** [comment]
@Gevaarlijk you can download latest app from the latest release. https://github.com/Sandip124/BatteryNotifier/releases/tag/v3.0.0
You can download the executable and it will run automatically without needing of ling installation process.

**Comment by Gevaarlijk** [comment]
There is no exe file in the zip. 

Is there not a portable version? I don't want to have to install something.

**Comment by Sandip124** [comment]
> There is no exe file in the zip.
> 
> Is there not a portable version? I don't want to have to install something.
Portable version of this app is not available, use the installer intead.

**Comment by Gevaarlijk** [comment]
Okay, I got here through a link from a source claiming it was portable.

If anyone knows of similar software that actually is portable let me know.
